
export default {
    signUp: `/api/v1/auth/register`,
    logIn:`/api/v1/auth/login`,
    forgotPassword: `/api/v1/auth/forgotPassword`,
    confirmPassword: `/api/v1/auth/confirm-forgot-password`,
    getUserAccountDetails:`/api/v1/profile`,
    getAllUsers:`/api/v1/profile/all`,
    updateUserAccountDetails: `/api/v1/profile`,
    addUserProfilePicture : `/api/v1/profile/picture`,
    changePassword: `/api/v1/profile/changepassword`,
    addAmc : `/api/v1/enquiry/amc`,
    getAmc: `/api/v1/enquiry/amc/all`,
    deleteAmc: `/api/v1/enquiry/amc/delete`,
    addContactUs:`/api/v1/enquiry/contactUs`,
    getContactUs:`/api/v1/enquiry/contactUs/all`,
    deleteContactUs:`/api/v1/enquiry/contactUs/delete`,
    addProject:`/api/v1/property/project/add`,
    getProject:`/api/v1/property/project/get`,
    getByProject:`/api/v1/property/project`,
    deleteProject: `/api/v1/property/project/delete`,
    updateProject:`/api/v1/property/project/edit`,
    addProjectEnquiry:`/api/v1/property/project/enquiry`,
    getProjectEquiry:`/api/v1/property/project/enquiryall`,
    deleteProjectEnquiry:`/api/v1/property/project/enquirydelete`,
    addTestimony:`/api/v1/testimony/add`,
    getTestimony:`/api/v1/testimony/get`,
    deleteTestimony:`/api/v1/testimony/delete`,
    updateTestimony: `/api/v1/testimony/edit`,
    addProperty:`/api/v1/property/add`,
    getProperty: `/api/v1/property/get`,
    deleteProperty:`/api/v1/property/delete`,
    singleProperty: `/api/v1/property/singleProperty`,
    updateProperty: `/api/v1/property/updateProperty`,
    getPropertyByTypePro: `/api/v1/property/getbytype`,
    getPropertyBySearch: `/api/v1/properties`,
    getPropertytoShow: `/api/v1/properties/show`,
    getPropertyByPrice:`/api/v1/property/range`,
    changeStatus: `/api/v1/property/chageStatus`


}
